### ISSUE TITLE
Threshing speeddoubled

### ISSUE THREAD

**Issue by Dzi4d3k** [Mogli12/AutoCombine#4]
Hello,

After last update (11.09) I'm observing that combines go 2x faster. These are standard machines (NH CR 10.90), and when operated manually threshing speed is 10 km/h, but with autocombane the go 20 km/h.
I suppose that this is not intended change, right?

Regards.

**Comment by Mogli12** [comment]
You can adjust the speed of the combine with keys 1 & 2. AutoCombine ignores the limitation to 10 km/h coming from the cutter. So this is intended and was always part of AutoCombine.

**Comment by Dzi4d3k** [comment]
That explains my observations, thank you for answer. I can't imagine now how I missed this, but good to know. Case resolved :smile:
