### ISSUE TITLE
AutoCombine und Courseplay

### ISSUE THREAD

**Issue by mngrazy** [Mogli12/AutoCombine#5]
Hi Mogli

nutze die neuste version von autoCombine (von gestern ---> 4.0.9.1)
und courseplay 4.01.0109 (dev version)

einstellungen von autoCombine sind wie folgt (siehe screenshot)
http://up.picr.de/23128459pq.jpg

der courseplay experte kommt auch zum abtanken
wenn am ende vom feld der drescher noch nicht leer ist , wartet der courseplay fahrer bis der drescher leer ist
sobald der drescher leer ist , dreht courseplay durch

ZZZ_courseplay/mode2.lua:517: attempt to index a nil value

auszug aus der lua

local dirX,dirZ = combine.acDirectionBeforeTurn.trace[index].dx,combine.acDirectionBeforeTurn.trace[index].dz

hast du da eventuell was an der autoCombine geändert , da es mit einer älteren autoCombine lief (weiss aber nicht mehr welche version es war)

grüsse grazy

**Comment by Mogli12** [comment]
Hi, Grazy,

interessant, auf welche Variablen Courseplay da zugreift. Selber nutze ich das so gar nicht. Es sollte aber jetzt korrigiert sein.

Viele Grüße
